"""Add file_path to Information model

Revision ID: 9a85182c8937
Revises: c00dff9f0671
Create Date: 2024-12-02 10:35:38.201125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a85182c8937'
down_revision = 'c00dff9f0671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('file_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('information', 'file_path')
    # ### end Alembic commands ###
